# Generated by Django 5.2.17 on 2026-09-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_backfill_organizations"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=100)),
                ("max_payment_links_per_month", models.PositiveIntegerField(default=3)),
                ("ai_content_quota", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktyvi"),
                            ("past_due", "Vėluoja mokėjimas"),
                            ("canceled", "Atšaukta"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
        ),
    ]
