# Generated by Django 6.0.9 on 2026-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='twilio_from_number',
            field=models.CharField(blank=True, help_text="This organization's own Twilio SMS sender number (E.164, e.g. +15551234567). Leads only receive SMS once this is set, so each organization's messages come from a number specific to them rather than a number shared across all tenants.", max_length=20),
        ),
    ]
