# Generated by Django 6.0.6 on 2026-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
