# Generated by Django 6.0.6 on 2026-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Sistema', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='kind',
            field=models.CharField(choices=[('note', 'Pastaba'), ('call', 'Skambutis'), ('email', 'El. laiškas'), ('message', 'Žinutė')], default='note', max_length=20),
        ),
    ]
