# Generated by Django 6.0.6 on 2026-06-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_comment_author_comment_kind'),
    ]

    operations = [
    ]
