# Generated by Django 5.2.17 on 2026-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_backfill_organizations"),
        ("crm", "0011_alter_activity_id_alter_activity_lead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="accounts.organization",
            ),
        ),
    ]
